### PR TITLE
Add basic acceptance test for index route

### PR DESCRIPTION
**Pull request by botandrose**
So this is surely awful, but its a first stab at something, and I'm interested in your feedback.

### CODE REVIEW

**Comment by botandrose** [comment]
So here's what I'd like to accomplish next:
* Configure the upload dir for test mode, so we can run it in e.g. `/tmp/rocket-pastbin-ab9a8sdf98asdf`.
* Get Travis (or something similar) going
* Refactor tests to be in their own separate module file
* Clean up assertion API and extract to its own module

Longer-term:
* Test the user workflow at a higher-level, something like: Load homepage, see that there are no uploads, upload something, see that there are uploads, download the something. Capybara-like API is the goal. Probably need to run a separate process that hits it over the network in a black-box fashion, instead of knowing implementation details e.g. this is a rocket app, but one step at a time.

Thoughts?

**Comment by BartMassey** [comment]
Should the new Rocket dev-dependencies be on 0.1.3?

**Comment by botandrose** [comment]
Yes, indeed. Good catch!

**Comment by BartMassey** [comment]
Thanks for the patches. They read fine.

The assert_no_selector() test is failing, though. It counts 5 rather than 0 instances of the selector.

**Comment by botandrose** [comment]
Yes, that's because of the first point I raised above

**Comment by BartMassey** [comment]
The configurable upload dir? OK. Do you want it to be a compile-time thing, or a command-line argument, or an environment variable, or some combination of these? All are quite easily achievable...

**Comment by botandrose** [comment]
I feel like it should be configurable as part of the test setup, but that could be my dynamic language bias talking.

**Pull request merged**
